name: "Github Pages"
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    # container: djmolitor/housing-prices:v2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Verify git repo
        run: |
          ls -l
          git rev-parse --is-inside-work-tree
