name: "Github Pages"
on:
  push:
    branches:
      - main

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"
  
  publish:
    needs: configure
    runs-on: ubuntu-latest
    container:
      image: djmolitor/housing-prices:v2
      options: --user ${{ needs.configure.outputs.uid_gid }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install R Dependencies
        shell: Rscript {0}
        run: |
          install.packages("renv")
          renv::install()
      
      - name: Install Python Dependencies
        run: |
          python3.10 -m venv pyenv
          . ./pyenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Render Quarto Project
        run: |
          quarto render index.qmd
          mkdir _site
          mv index.html _site
        env:
          QUARTO_PYTHON: ./pyenv/bin/python
      
      - name: Install rsync
        run: |
          apt-get update && apt-get install -y rsync

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site