name: "Github Pages"
on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  publish:
    runs-on: ubuntu-latest
    container: djmolitor/housing-prices:v1
    steps:
      - name: Install Git
        run: apt-get install -y git

      - name: Diagnostics
        run: |
          ls pyenv
          echo $QUARTO_PYTHON

      - name: Render Quarto Project
        run: quarto render index.qmd

      - name: Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: ./index.html
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}