name: "Github Pages Docker"
on:
  push:
    branches:
      - main

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"
  
  publish:
    needs: configure
    runs-on: ubuntu-latest
    container:
      image: djmolitor/housing-prices:v2
      options: --user ${{ needs.configure.outputs.uid_gid }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Render Quarto Project
        run: |
          quarto render index.qmd
          mkdir _site
          mv index.html _site
      
      - name: Create .nojekyll
        run: |
          echo "" >> _site/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site