name: "Github Pages"
on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  publish:
    runs-on: ubuntu-latest
    container: djmolitor/housing-prices:v2
    steps:
      - name: Install Git
        run: apt-get install -y git

      - name: Install R Dependencies
        shell: Rscript {0}
        run: |
          install.packages("renv")
          renv::install()
      
      - name: Install Python Dependencies
        run: |
          python3.10 -m venv pyenv
          . ./pyenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Render Quarto Project
        run: quarto render index.qmd

      - name: Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: ./index.html
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}