name: "Github Pages"
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    container: djmolitor/housing-prices:v2
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Git
        run: apt-get install -y git

      - name: Install R Dependencies
        shell: Rscript {0}
        run: |
          install.packages("renv")
          renv::install()
      
      - name: Install Python Dependencies
        run: |
          python3.10 -m venv pyenv
          . ./pyenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Render Quarto Project
        run: |
          quarto render index.qmd
          mkdir _site
          mv index.html _site
        env:
          QUARTO_PYTHON: ./pyenv/bin/python

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}